### ISSUE TITLE
Wood

### ISSUE THREAD

**Issue by DragonTamr34** [danikk14g/Craftologia#3]
Is the rubber wood supposed to be crafted into four planks without an axe?

**Comment by dancc7t** [comment]
yes, i did only rework the vanilla wood, which is the one you need the most during the early game, changing the recipes for all the wood types and its parts would be too much of a pain both for me and for the players.
There is also a [discord server](https://discord.gg/7Tgy2NB), i am more available there if you have any more doubts. Thanks.

**Comment by DragonTamr34** [comment]
Okay, I am just not comfortable enough yet to use discord. Also, I discovered that double tall grass drops the seeds. Thanks for the response back.
