### ISSUE TITLE
Mining

### ISSUE THREAD

**Issue by DragonTamr34** [danikk14g/Craftologia#4]
Do you have any mining techniques for mining ore? I am having trouble finding any even though I know what biome they spawn in.
This is my mining setup. I am doing this for every four y levels I go down. If you have a better way I would like to know as this is super time consuming and probably inefficient.
![2018-10-27_19 39 31](https://user-images.githubusercontent.com/34604466/47610332-a6614000-da20-11e8-9596-2e23ff39759e.png)

**Comment by dancc7t** [comment]
do you remember when you did generete (version-wise) those chunks?
what tool are you using?

Lavender fields is one of the least ore populated biomes, it just contains lead, galena and aluminium, not even the basic vanilla ores (redstone, lapis and diamond generate in every Overworld biome). In fact is one of the worst biomes to go mining.

That exhaustive/saturation mining techique is only useful if you want to find certain ores which generate in very small clusters at a very close altitude (such as wolframite or rutile), but in general the way to go mining is going a straight line with a 3x3 or 5x5 tool and you will find eventually ores. 

Vanilla mining techniques are good for vanilla, in this pack, you can go like this:
![2018-10-28_02 58 36](https://user-images.githubusercontent.com/26232044/47610773-6e282480-da55-11e8-82c1-23696faca884.png)
![2018-10-28_02 59 22](https://user-images.githubusercontent.com/26232044/47610775-74b69c00-da55-11e8-8e46-fd22f3b28949.png)

Until you have OP machines, draw 5x5 parallel lines with 3 blocks separation, that should be enough.

**Comment by DragonTamr34** [comment]
I do not remember when I generated those chunks as I have taken a break for a while. I was using a stone pick before I made a tinkers stone pick. I am still very early game and I do not think I have a 3x3 option yet. I am mining in that biome because it was close and I needed aluminum. I cannot build a tinkers hammer because I lack the resources to build the tool forge.

**Comment by dancc7t** [comment]
Can you see the questbook like this? 
![2018-10-28_10 05 14](https://user-images.githubusercontent.com/26232044/47614106-73f42900-da9a-11e8-91e8-3e4bcdea26c8.png)
If not then you have to run this command (requires creative mode):
`/bq_admin default load`

On next update there will be an option to complete a checkbox quest which grants you that command as reward, you can complete the quest infinite times, so there is no more need to swtich modes to run the command manually.

For TiC there is only one material displayed per part and table, it does not mean you can only craft them with electrical steel, maybe i did not explain this good enogh in the guidebook and the recipe tooltip. But you can actually craft only two tables using 4 ingots instead of 4 blocks, this is because i just changed two recipes for them.
![2018-10-28_10 09 04](https://user-images.githubusercontent.com/26232044/47614129-009ee700-da9b-11e8-9ee1-61de29017633.png)
i will also add this cheaper recipe for gold, steel and bronze tables for the next update

**Comment by DragonTamr34** [comment]
Oh, okay. I did not know there was a tool forge recipe that used iron ingots instead of electrical steel or other later alloys. My questbook does look like that one aside from the reload quest database part. Thank you, this will make progressing much easier and not quite as tedious. One other question, how do you make the slimesling? I have not gotten far enough to unlock the quest as I still need to hunt a blizz so I do not know if you explain how. I do have the boots I just do not know how to get the slime string.

**Comment by dancc7t** [comment]
I guess it was my faut not to make it clear from the beginning,  JEI only shows electrical steel but it does not mean you cant use other materials to make the tool forget.
![2018-10-28_20 15 10](https://user-images.githubusercontent.com/26232044/47620796-c9f2bc00-daee-11e8-8d84-442fc07f2920.png)

There is just the mob hunting quest, no more info, i will add some info to the slimesling quest, but here is how to make the slime vine (any of the slime vines works)
![2018-10-28_20 22 04](https://user-images.githubusercontent.com/26232044/47620842-8f3d5380-daef-11e8-860b-7fd2b07351e4.png)

**Comment by DragonTamr34** [comment]
Oh so you use actual vines, I was trying to use slimeballs and slime crystals. Do you know what biomes blizzs spawn in? I am having trouble finding them and they are very useful for getting cryotheum. Another thing is trying to get the pack to run smoothly. I know I am asking many questions on single issues but I don't want to spam issues if they can easily be fixed. My computer has an intergrated graphics card and 16 gigs of RAM. I am currently using the twitch launcher which has preset JVM args. I used a part of your args since twitch already has the memory ones by default. I am alsousing the JAR launcher so I can use the 64-bit Java I have over the 32-bit. Aside from getting a new graphics card I have no idea what to do. It does run at ~50-60 fps but drops and mobs jump along with blocks reappearing when broken.

**Comment by dancc7t** [comment]
Minecraft, even though is CPU intensive, does heavily rely on GPU aswell.
I have a intel i7 7700k (with integrated graphics) which can run modded minecraft at 30-80fps most of the time, but fps drop a lot when looking at places with many microblocks/tile entities. 
I got myself a decent GPU and the framrate jumped like +150. In my survival of Craftologia i have 180fps most of the time. 
You can also install Optifine (it does helps a lot) and lower some of the graphic settings. Here are mine:
![optifine_settings](https://user-images.githubusercontent.com/26232044/47668934-ff101480-dba9-11e8-99ba-4bd6e9def11f.png)

**Comment by DragonTamr34** [comment]
Yeah, I have a lot of those settings off or set to fast. I do not remember my CPU model or integrated graphics type but it is an Intel i5. Minecraft modpacks just eat up my RAM and I believe this is caused by the CPU having to use more RAM to make up for the lack of a dedicated GPU. Other games also run very poorly for me but it is not a gaming computer. With that said it still is playable to a degree. For BetterFPS are you using a different Algorithm? Are blizzs still in cold biomes, I found a blitz but that was different.

**Comment by dancc7t** [comment]
Yes, integrated graphics require system memory to perform the operations. This pack is not a lightweight  nor a heavy one, and i want to keep the modlist below 160. I have already planned 7 mods additions and and 5 removals in what will probably be the last big change (mod-wise) to the pack, next update i will also add a list of what mods can be safely removed from the pack on the Guidebook.

I think i use Ryven's Half Algorithm

https://teamcofh.com/docs/thermal-foundation/blizz/
