### ISSUE TITLE
Reloading chunks using MCedit

### ISSUE THREAD

**Issue by DragonTamr34** [danikk14g/Craftologia#5]
For some reason opening the level.dat with MCedit for this modpack leaves huge holes and everything loads wrong. I have tried using MCedit with other packs and everything looks the same as in the game. I am trying to delete chunks so that the ore generation will kick in after the fix. If you know another way of regenerating the chunks/ore gen I will try and see if that works.

**Comment by dancc7t** [comment]
can you show me how that looks?

**Comment by DragonTamr34** [comment]
This is a 1.12.2 modpack that I have played:
![screenshot 5](https://user-images.githubusercontent.com/34604466/47621392-7cb22280-dacd-11e8-8c92-9ab8282ee6ab.png)
And this is Craftologia:
![screenshot 6](https://user-images.githubusercontent.com/34604466/47621395-89cf1180-dacd-11e8-9f76-0437c6d6e6ec.png)

**Comment by dancc7t** [comment]
first image is only rendering vanilla blocks, there are no modded blocks, but in the second image it looks you are rendering a BOP biome, MCEdit does not render modded blocks if i remember correctly. For some reason a lot of blocks are not being shown, it might have to do with JEID (it uses 1.13 ID's), who knows, anyways there shouldnt be any problem if you go to the chunk view and prune the chunks.

I can tell you that 1.3.0 or 1.3.a update will both add and remove several mods and feature some big oregen changes, but those changes affecting the Overworld will not be probably tagged with retrogen. You might prefer to wait until then, as all changes i have been making until now use retrogen so people dont have to delete any chunks or explore far away to see the oregen changes.

**Comment by DragonTamr34** [comment]
I still do not know why the vanilla logs or villager houses are rendered in granite and stone or why stone and dirt aren't rendered at all. Going to the chunk view shows the same thing even for vanilla biomes like plains or forest. Even the oceans don't exist. If I still wait for the next update I won't be able to safely prune or reload chunks because I won't know where my base is. Is there another way to regen the chunks so any new oregen configs can take place? It may be a MCedit problem but it works with ohter packs which is why I am asking you.

**Comment by dancc7t** [comment]
well, in my case it happens the same, probably cause MCEdit does not properly recognize 1.13 ID's which JEID uses. If you want to safely prun everything except your base place yourself in the middle of your base and then go to the chunk view and select a square of 64x64 chunks, you can make backups and try different pruns and choose whichever looks less weird.

**Comment by DragonTamr34** [comment]
That will probably be what I end up doing. I will just have to count properly and hope I miss my base, which is in a village temporarily.
